config/routes.rb
Rails.application.routes.draw do
  resources :health_categories do
    resources :individual_sections
  end
end

app/models/health_category.rb
class HealthCategory < ActiveRecord::Base
  has_many :individual_sections
  validates :category, :presence => true
end

app/models/individual_section.rb
class IndividualSection < ActiveRecord::Base
  belongs_to :health_category
  validates :title, :presence => true
  validates :content, :presence => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/health_categories_controller.rb
class HealthCategoriesController < ApplicationController
  def index
    @health_categories = HealthCategory.all
  end

  def show
    @health_category = HealthCategory.find(params[:id])
  end


  def new
    @health_category = HealthCategory.new
  end

  def create
    @health_category = HealthCategory.new(health_category_params)
    if @health_category.save
      flash[:notice] = "You've added a new category to Inner Health!"
      redirect_to health_categories_path
    else
      render :new
    end
  end

  def edit
    @health_category = HealthCategory.find(params[:id])
  end

  def update
    @health_category = HealthCategory.find(params[:id])
    if @health_category.update(health_category_params)
      redirect_to health_categories_path
    else
      render :edit
    end
  end

  private
  def health_category_params
    params.require(:health_category).permit(:category, :image_url)
  end
end

app/controllers/individual_sections_controller.rb
class IndividualSectionsController < ApplicationController

  def new
    @health_category = HealthCategory.find(params[:health_category_id])
    @individual_section = @health_category.individual_sections.new
  end

  def show
    @health_category = HealthCategory.find(params[:health_category_id])
    @individual_section = IndividualSection.find(params[:id])
  end

  def create
    @health_category = HealthCategory.find(params[:health_category_id])
    @individual_section = @health_category.individual_sections.new(individual_section_params)
    if @individual_section.save
      flash[:notice] = "Section successfully added"
      redirect_to health_category_path(@health_category.id)
    else
      render :new
    end
  end

  def edit
    @health_category = HealthCategory.find(params[:health_category_id])
    @individual_section = IndividualSection.find(params[:id])
  end

  def update
    @health_category = HealthCategory.find(params[:health_category_id])
    @individual_section = IndividualSection.find(params[:id])
    if @individual_section.update(individual_section_params)
      redirect_to health_category_path(@health_category.id)
    else
      render :edit
    end
  end

  def destroy
    @health_category = HealthCategory.find(params[:health_category_id])
    @individual_section = IndividualSection.find(params[:id])
    @individual_section.destroy
    redirect_to health_category_path(@health_category.id)
  end

  private
  def individual_section_params
    params.require(:individual_section).permit(:title, :content, :media, :media_description)
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/health_categories/_form.html.erb
<%= render "layouts/errors", :object => @health_category %>

<%= form_for @health_category do |f| %>
  <%= f.label :category %>
  <%= f.text_field :category %>
  <br>
  <%= f.label :image_url %>
  <%= f.text_field :image_url %>
  <br>
  <%= f.submit %>
<% end %>

app/views/health_categories/edit.html.erb
<h1><%= @health_category.category %></h1>

<%= render 'form' %>

app/views/health_categories/index.html.erb
<div id="container">
  <h1>Inner Health</h1>


  <% @health_categories.each do |health_category| %>
    <div class="col-md-3">
      <h5><%= link_to health_category.category, health_category_path(health_category) %></h5>
      <img src="<%= health_category.image_url %>">
    </div>
  <% end %>
  <br>
  <%= link_to "Add new category", new_health_category_path %>
</div>

app/views/health_categories/new.html.erb
<h1>Add new category</h1>

<%= render 'form' %>

app/views/health_categories/show.html.erb
<h1><%= @health_category.category %></h1>

<% if @health_category.individual_sections.any? %>
  <% @health_category.individual_sections.each do |section| %>
    <h5><%= link_to section.title, health_category_individual_section_path(@health_category, section) %></h5>
  <% end %>
<% else %>
  <p>
    There are no articles in this section yet.
  </p>
<% end %>

<br>
<p><%= link_to "Add an article to Inner Health", new_health_category_individual_section_path(@health_category) %></p>
<p><%= link_to "See all health categories", health_categories_path %></p>

<p><%= link_to "Edit this category", edit_health_category_path(@health_category) %></p>

app/views/individual_sections/_form.html.erb
<%= render "layouts/errors", :object => @individual_section %>

<%= form_for [@health_category, @individual_section] do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <br>
  <%= f.label :content %>
  <%= f.text_field :content %>
  <br>
  <%= f.label :media %>
  <%= f.text_field :media %>
  <br>
  <%= f.label :media_description %>
  <%= f.text_field :media_description %>
  <br>
  <%= f.submit %>
<% end %>

app/views/individual_sections/edit.html.erb
<h1><%= @individual_section.title %></h1>

<%= render "form" %>

app/views/individual_sections/new.html.erb
<h1>Add a new section to Inner Health</h1>

<%= render "form" %>

app/views/individual_sections/show.html.erb
<h1><%= @individual_section.title %></h1>

<img src="<%= @individual_section.media %>">

<p>
  <%= @individual_section.content %>
</p>

<p><%= link_to "See all articles in this category", health_category_path(@health_category) %></p>

<p><%= link_to "Edit this page", edit_health_category_individual_section_path %></p>
<p><%= link_to "Delete this page", health_category_individual_section_path(@health_category, @individual_section),
:data => {:confirm => "You sure?",
:method => "delete"} %></p>

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
<h3>Please fix these errors</h3>
<ul>
  <% object.errors.full_messages.each do |message| %>
  <li><%= message %></li>
  <% end %>
</ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>HealthyTimes</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= flash[:alert] %>
<%= flash[:notice] %>

<%= yield %>

</body>
</html>